### ISSUE TITLE
Fix the project description

### ISSUE THREAD

**Issue by mikaelhg** [Yleisradio/yle-api-template#13]
![Apostrophe's](http://www.angryflower.com/bobsqu.gif)

**Comment by lasiltan** [comment]
![image](https://cloud.githubusercontent.com/assets/2161725/26588338/b8aef24c-455d-11e7-8c4b-b81c111e5168.png)

**Comment by mikaelhg** [comment]
![screen shot 2017-05-30 at 17 32 14](https://cloud.githubusercontent.com/assets/264506/26588438/02f566b0-455e-11e7-96a7-8591183e237d.png)

**Comment by lasiltan** [comment]
Done
